### ISSUE TITLE
Missing scopes on punctuation

### ISSUE THREAD

**Issue by chbk** [REditorSupport/atom-language-r-legacy#10]
I use r a lot so this package is great, is it still being developed?

If so, I noticed missing scopes on `()` `,`:
```r
sub("_", "", path)
getrootdir(utils::untar(src))
data.frame()
file.exists()
```
They should be `punctuation.definition.parameters.bracket.round.begin|end`, `punctuation.separator.parameters.comma` based on [docs](https://github.com/atom/flight-manual.atom.io/pull/114).

**Comment by randy3k** [comment]
I am sure that @kylebarron and @guillaumechaumet are still working on it.

**Comment by kylebarron** [comment]
I've been focusing my efforts recently on Stata packages ([1](atom.io/packages/language-stata), [2](https://atom.io/packages/stata-exec)) since I'm required to use that language most of the time in my work. I hope to find time to work on this in the next month or two.

Also note that this currently isn't the repository that [language-r](url) is sourced from. See [this issue](https://github.com/lee-dohm/language-r/issues/25) for relevant discussion.

I also just noticed that @lee-dohm archived that repository, so I'm not sure if there's any hope of ever having this copy becoming upstream. Creating a maintained fork might be hard to gain traction.

Thoughts @guillaumechaumet ?

**Comment by randy3k** [comment]
We are waiting @lee-dohm to transfer the ownership of his repo to REditorSupport so we can inherit the atom package name `language-r`. I hope that we have already convinced him and showed our interests in maintaining it.

**Comment by guillaumechaumet** [comment]
I was working on backticks definition since I have seen some strange behaviour. I will look into language-ruby to find some good examples.

**Comment by guillaumechaumet** [comment]
I try to improve r.cson for punctuation definition. I have still an issue with back-tick scope. For example \`#variable\` appeared as comment where '#variable' don't. Any solution?

**Comment by randy3k** [comment]
This issue was moved to REditorSupport/atom-language-r#7
